"""build auth module

Revision ID: 1e6f472c35e1
Revises: a1ca05425882
Create Date: 2026-01-17 18:06:03.153981

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1e6f472c35e1'
down_revision: Union[str, Sequence[str], None] = 'a1ca05425882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('token', sa.String(), nullable=False),
                    sa.Column('blacklisted_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('expires_at', sa.DateTime(timezone=True),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'],
                    unique=False)
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist',
                    ['token'], unique=True)
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('is_superuser', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.alter_column('book', 'title',
                    existing_type=sa.VARCHAR(length=100),
                    type_=sa.String(length=50),
                    existing_nullable=False)
    op.alter_column('book', 'author',
                    existing_type=sa.VARCHAR(length=100),
                    type_=sa.String(length=50),
                    existing_nullable=False)
    op.alter_column('book', 'description',
                    existing_type=sa.VARCHAR(length=200),
                    type_=sa.String(length=255),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade schema.
    No downgrade for this migration.
    """
    pass
